# Generated by Django 5.1.4 on 2024-12-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0005_alter_review_book_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
